'use strict';
  /** Script Provided by https://github.com/caceresjayder */
  /** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface: any, Sequelize: any) {
    await queryInterface.createTable('transactions', {
      id: {
        type: Sequelize.INTEGER,
        allowNull: false,
        primaryKey: true,
        autoIncrement: true,
        _autoGenerated: 'undefined',
      },
      to: {
        type: Sequelize.STRING,
      },
      from: {
        type: Sequelize.STRING,
      },
      amount: {
        type: Sequelize.INTEGER,
      },
      concept: {
        type: Sequelize.ENUM('DEPOSIT', 'TRANSFER')
      },
      createdAt: {
        type: Sequelize.DATE,
        allowNull: false,
        _autoGenerated: 'undefined',
      },
      updatedAt: {
        type: Sequelize.DATE,
        allowNull: false,
        _autoGenerated: 'undefined',
      },
    });
  },

  async down (queryInterface: any, Sequelize: any) {
    await queryInterface.dropTable('transactions');
  },
};
