'use strict';
  /** Script Provided by https://github.com/caceresjayder */
  /** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface: any, Sequelize: any) {
    await queryInterface.createTable('users', {
      id: {
        type: Sequelize.INTEGER,
        allowNull: false,
        primaryKey: true,
        autoIncrement: true,
        _autoGenerated: 'undefined',
      },
      name: {
        type: Sequelize.STRING,
      },
      email: {
        type: Sequelize.STRING,
        unique: true,
        allowNull: false,
        validate: {
          isEmail: true,
        },
      },
      password: {
        type: Sequelize.STRING,
        min: '8',
      },
      balance: {
        type: Sequelize.INTEGER,
        defaultValue: '0',
      },
      role: {
        defaultValue: 'USER',
        type: Sequelize.ENUM('ADMIN', 'USER', 'WORKER')
      },
      status: {
        defaultValue: 'ACTIVE',
        type: Sequelize.ENUM('ACTIVE', 'DISABLED')
      },
      createdAt: {
        type: Sequelize.DATE,
        allowNull: false,
        _autoGenerated: 'undefined',
      },
      updatedAt: {
        type: Sequelize.DATE,
        allowNull: false,
        _autoGenerated: 'undefined',
      },
    });
  },

  async down (queryInterface: any, Sequelize: any) {
    await queryInterface.dropTable('users');
  },
};
